# Build and publish a package to Github Packages

name: ci-net-pack-push-webapp-other-repo

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      GITHUB_NUGET_URL: https://nuget.pkg.github.com/${{ GITHUB.REPOSITORY_OWNER }}/index.json      

    steps:
    - name: Get build Info
      id: info
      run: |
          echo "buildyear=$(date +'%Y')" >> $GITHUB_OUTPUT
          echo "builddate=$(date +'%m%d%H%M')" >> $GITHUB_OUTPUT
          echo "version=$(date +'%Y').$(date +'%m').$(date +'%d').$(date +'%H%M')" >> $GITHUB_OUTPUT
    
    - name: Checkout source
      uses: actions/checkout@v4
      with:
        path: PocGithubActions

    - name: Checkout source PocGithubActionsDotNet
      uses: actions/checkout@v4
      with:
        repository: juanonsoftware/PocGithubActionsDotNet
        path: PocGithubActionsDotNet
 
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
 
    - name: Restore dependencies
      run: dotnet restore PocGithubActionsDotNet
  
    - name: Build
      run: dotnet build PocGithubActionsDotNet --no-restore -c Release   
      
    - name: Test
      run: dotnet test PocGithubActionsDotNet -c Release --no-build --verbosity normal --logger "html;logfilename=TestResult-${{ steps.info.outputs.buildyear }}-${{ steps.info.outputs.builddate }}.html"

    - name: Publish SampleWebApplication
      run: dotnet publish ${{ github.workspace }}/PocGithubActionsDotNet/SampleWebApplication/SampleWebApplication.csproj -c Release --no-build -o ${{ github.workspace }}/PublishedSampleWebApplication

    - name: Create SampleWebApplication Zip package 🐙
      uses: OctopusDeploy/create-zip-package-action@v3
      with:
        package_id: 'SampleWebApplication'
        version: '1.0.${{ steps.info.outputs.buildyear }}.${{ steps.info.outputs.builddate }}'
        output_folder: '${{ github.workspace }}/Packaging'
        base_path: ${{ github.workspace }}/PublishedSampleWebApplication
        files: |
          **/*.*

    - name: Build nuspec file
      run: cp ${{ github.workspace }}/PocGithubActions/NuSpecs/SampleWebApplication.nuspec ${{ github.workspace }}/Packaging

    - name: Build nuget package
      run: NuGet pack cp ${{ github.workspace }}/PocGithubActions/NuSpecs/SampleWebApplication.nuspec -OutputDirectory ${{ github.workspace }}/Packaging

   # - name: Push packages
   #   run: dotnet nuget push ${{ github.workspace }}/*.nupkg --source ${{ env.GITHUB_NUGET_URL }}  --api-key ${{ secrets.PAT_PUSH_PACKAGES }}

  
