name: ci-netfx-other-public-repo

on:
  workflow_dispatch:
  push:
    branches: [ "" ]
  pull_request:
    branches: [ "" ]

jobs:
  build:

    runs-on: windows-latest
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

    steps:
    
    - name: Install netfx-4.8
      run: choco install netfx-4.8

  
    - name: Get .NET FX versions
      shell: pwsh
      run: |
        Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\NET Framework Setup\NDP' -Recurse | Get-ItemProperty -Name version -EA 0 | Where { $_.PSChildName -Match '^(?!S)\p{L}'} | Select PSChildName, Version
        
    - name: Checkout the repo
      uses: actions/checkout@v4
      with: 
        repository: vndevpro/architecture-common
