name: ci-netfx-other-public-repo

on:
  workflow_dispatch:
  push:
    branches: [ "" ]
  pull_request:
    branches: [ "" ]

jobs:
  build:

    runs-on: windows-latest
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

    steps:
    
    - name: Install netfx-4.8
      run: choco install netfx-4.8

  
    - name: Display system info
      shell: pwsh
      run: |
        Write-Host "System.Environment.Version"
        [System.Environment]::Version

        Write-Host "PSVersionTable"
        $PSVersionTable
        
    - name: Checkout the repo
      uses: actions/checkout@v4
      with: 
        repository: vndevpro/architecture-common
